# ruff: noqa: E501

from __future__ import annotations

from typing import Any

from app.services.generation_settings import DEFAULT_GENERATION_SETTINGS, SETTING_RANGES


def settings_export_ai_editing_guide() -> dict[str, Any]:
    return {
        "purpose": (
            "这份 JSON 是 RPGForge 单个游戏的剧本与运行设定导出。"
            "它适合交给 AI 阅读和编辑，也可以原样导入回 RPGForge。"
        ),
        "import_behavior": (
            "当前导出默认 import_mode=replace_all。导入时会读取并覆盖 game、"
            "system_prompt、generation_notes、generation_settings、worldview、"
            "script_outline、lore_entries、modes、characters 等业务字段。"
            "replace_all 下不会把旧 script_outline 的用户简报、必须保留、禁止偏离或角色档案补回来。"
            "_ai_editing_guide 和 _field_guide 只是说明，导入会忽略。"
        ),
        "must_keep_valid_json": [
            "必须保持标准 JSON 合法。",
            "不要加入 Markdown 标题、// 注释、# 注释、尾逗号或未转义换行。",
            "字符串内部如果需要换行，请使用 \\n。",
            "不要删除 format_version，也不要改成未知版本。",
            "不要删除 import_mode；如果希望 JSON 成为导入后的最终设定，保持 replace_all。",
        ],
        "editing_priority": [
            "这份导出的 JSON 是完整设定源；你改成什么，replace_all 导入后就以什么为准。",
            "优先检查并统一用户创作意图、必须保留内容、禁止偏离方向和正典词条，避免同一设定在多个字段互相矛盾。",
            "如果要改剧情方向，先改 campaign_contract，再同步 acts、truth_map、clue_ladder、pressure_clock 和 lore_entries。",
            "如果要让 AI 更稳地判断何时进入下一幕，在 script_outline.acts[].completion_anchors 中补齐当前幕完成锚点。",
            "如果只想改变文风或输出长度，优先改 generation_notes、story_contract 或 generation_settings。",
            "如果只想改变某类行动的处理方式，优先改 modes[].injection。",
        ],
        "preserve_constraints": [
            "replace_all 不会自动保护旧约束；如果删除 must_preserve、must_not_become、forbidden_drift 或 user_brief，它们会按删除后的结果生效。",
            "script_outline.user_brief 记录用户原始需求，除非用户明确要求，不建议删除。",
            "script_outline.campaign_contract.must_preserve、must_not_become 和 forbidden_drift 是防跑偏边界，删改前要确认这是用户想要的新方向。",
            "不要把 gm_secret、hidden truth、幕后真相写进 public_info、worldview.summary 或玩家初始可见内容。",
        ],
        "lore_editing_rules": [
            "lore_entries 是可被 GM 检索和注入的剧本素材，不是普通百科。",
            "public_info 写玩家可见或可公开得知的信息。",
            "gm_secret 写 GM 需要知道但不能直接剧透的信息。",
            "content 写真正要注入给 GM 的完整素材。",
            "usage_note 写何时使用、怎么给线索、哪些内容不能直接揭露。",
        ],
        "mode_editing_rules": [
            "modes 是行动风格规则，不是世界资料。",
            "triggers 用于匹配玩家输入。",
            "injection 应写成可执行的 GM 导演规则，例如调查给线索不给答案、社交遵守 NPC 欲望与恐惧。",
        ],
        "generation_settings_rules": [
            "这些数值会影响 GM 输出长度、段落、标题、重点标记数量、近期回合引用长度和 token 消耗。",
            "想让剧情更丰富时，可以小幅提高 narrative_target_min_chars 和 narrative_target_max_chars。",
            "想降低 token 消耗时，可以降低 recent_turn_excerpt_chars 或正文目标字数。",
            "不要把目标字数调得过高，否则响应会变慢且更容易消耗上下文。",
        ],
        "characters_import_note": (
            "characters 在 replace_all 导入中会覆盖角色导演档案。"
            "JSON 不复制头像文件本身，也不导入回合历史、当前状态或角色运行时进度。"
            "如果通过 id 匹配到同一角色，已有头像文件字段会保留。"
        ),
    }


def settings_export_field_guide() -> dict[str, Any]:
    guide = {
        "format_version": _field(
            label="导出格式版本",
            json_type="string",
            import_effective=True,
            purpose="让导入接口识别这是受支持的 RPGForge settings JSON。",
            story_impact="不影响剧情内容，但改错会导致导入失败。",
            fill_rule="保持原值 rpgforge.settings.v1，除非系统升级并明确要求修改。",
            import_behavior="导入时会校验；校验通过后不会写入游戏设定。",
            example="rpgforge.settings.v1",
        ),
        "import_mode": _field(
            label="导入模式",
            json_type="string",
            import_effective=True,
            purpose="决定导入时是完整覆盖当前设定，还是使用旧的保护式合并。",
            story_impact="replace_all 能确保 AI 修改后的 JSON 成为最终剧本设定；protected 会把部分旧强约束补回，适合旧文件兼容但不适合全量改稿。",
            fill_rule="保持 replace_all；只有明确想恢复旧兼容行为时才改成 protected。",
            import_behavior="导入时读取此字段控制导入策略，不作为游戏剧情字段保存。",
            accepted_values=["replace_all", "protected"],
            example="replace_all",
        ),
        "_ai_editing_guide": _field(
            label="AI 编辑总指南",
            json_type="object",
            import_effective=False,
            purpose="给 AI 阅读的整体编辑原则。",
            story_impact="不直接影响剧情，只有 AI 按照它编辑其他字段时才间接影响结果。",
            fill_rule="不要修改；它只是说明区。",
            import_behavior="导入时忽略。",
            example={"purpose": "说明这份 JSON 如何编辑。"},
        ),
        "_field_guide": _field(
            label="字段说明表",
            json_type="object",
            import_effective=False,
            purpose="逐字段说明用途、填写规则、导入效果和示例。",
            story_impact="不直接影响剧情。",
            fill_rule="不要修改；它只是说明区。",
            import_behavior="导入时忽略。",
            example={"game.title": {"label": "游戏标题"}},
        ),
        "game": _field(
            label="游戏基础信息",
            json_type="object",
            import_effective=True,
            purpose="保存资料页和 GM 上下文使用的基础标题、题材、简介和游戏记录状态。",
            story_impact="标题、题材和简介会影响 GM 对作品名称、题材边界和故事入口的理解；status 主要影响列表和记录状态展示。",
            fill_rule="保持简洁，不要把完整世界观塞进这里。",
            example={"title": "雾港旧案", "genre": "悬疑武侠", "description": "失忆镖师追查雨夜义庄旧案。", "status": "active"},
        ),
        "game.title": _field(
            label="游戏标题",
            json_type="string",
            import_effective=True,
            purpose="作品名称，显示在列表、资料页和导出文件名中。",
            story_impact="会成为 GM 识别本局主题的短锚点。",
            fill_rule="填写简短标题，不要超过一句话。",
            example="雾港旧案",
        ),
        "game.genre": _field(
            label="题材类型",
            json_type="string|null",
            import_effective=True,
            purpose="描述本局的题材或类型。",
            story_impact="影响 GM 的类型预期，例如悬疑、武侠、赛博朋克、宫廷权谋。",
            fill_rule="用 1 到 3 个题材词概括，避免写成长段设定。",
            example="黑暗武侠悬疑",
        ),
        "game.description": _field(
            label="一句话简介",
            json_type="string|null",
            import_effective=True,
            purpose="给本局一个简短故事入口。",
            story_impact="影响 GM 对开局冲突和主线方向的整体判断。",
            fill_rule="写一句话，不要写隐藏真相和完整剧透。",
            example="失忆镖师在雨夜义庄醒来，发现自己被卷入黑伞契约。",
        ),
        "game.status": _field(
            label="游戏记录状态",
            json_type="string",
            import_effective=True,
            purpose="记录游戏在列表和详情页显示的状态标签。",
            story_impact="不直接改变剧情内容，但会影响游戏记录显示和状态识别。",
            fill_rule="使用短标签，最多 32 个字符；通常保持 active、draft 或当前导出值。",
            example="active",
        ),
        "system_prompt": _field(
            label="GM 系统提示",
            json_type="string|null",
            import_effective=True,
            purpose="定义本局 GM 的最高层叙事身份、输出纪律和长期规则。",
            story_impact="强烈影响每回合叙事方式、边界遵守、行动选项和口吻。",
            fill_rule="写稳定规则，不要写一次性剧情；避免和 campaign_contract 冲突。",
            example="你是克制、悬疑、重视线索递进的文字 RPG GM。每回合给出可见剧情和 A/B/C/D 四个行动选项。",
        ),
        "generation_notes": _field(
            label="生成备注",
            json_type="string|null",
            import_effective=True,
            purpose="补充本局生成偏好和风格提示。",
            story_impact="影响文风、细节密度、节奏倾向和 GM 取舍。",
            fill_rule="写短而具体的偏好；不要替代强约束。",
            example="保持压抑、克制、线索驱动；不要过早揭露黑伞契约真相。",
        ),
        "generation_settings": _field(
            label="GM 输出与运行参数",
            json_type="object",
            import_effective=True,
            purpose="控制每回合 narrative 长度、段落、标题、重点标记和近期回合摘录长度。",
            story_impact="影响文本丰富度、阅读节奏、上下文消耗和生成时间。",
            fill_rule="只填写整数；缺失或越界会被系统归一化到允许范围。",
            example=DEFAULT_GENERATION_SETTINGS,
        ),
        "worldview": _field(
            label="世界观",
            json_type="object",
            import_effective=True,
            purpose="描述世界基础舞台、基调、核心冲突和题材语境。",
            story_impact="影响 GM 对世界呈现、气氛、地点和长期冲突的判断。",
            fill_rule="公开世界信息写在这里；不要把玩家不应知道的幕后真相写进 summary。",
            example={
                "summary": "雁回镇被旧案和黑伞传闻笼罩。",
                "tone": "冷峻悬疑",
                "setting": "雨夜后的边陲义庄",
                "core_conflicts": ["记忆缺口与旧案真相", "江湖秩序与黑伞契约"],
            },
        ),
        "worldview.summary": _field(
            label="世界观摘要",
            json_type="string",
            import_effective=True,
            purpose="给 GM 一个公开层面的世界概览。",
            story_impact="会频繁影响每回合氛围和背景解释。",
            fill_rule="只写玩家可逐步理解的公开背景，不要直接写最终真相。",
            example="雁回镇近年怪案频发，黑伞客传闻与失踪镖队有关。",
        ),
        "worldview.tone": _field(
            label="世界基调",
            json_type="string",
            import_effective=True,
            purpose="定义世界呈现的情绪和审美倾向。",
            story_impact="影响措辞、画面感、冲突强度和恐怖/浪漫/热血比例。",
            fill_rule="使用明确风格词，避免互相矛盾。",
            example="冷峻、压抑、线索驱动",
        ),
        "worldview.setting": _field(
            label="初始舞台",
            json_type="string",
            import_effective=True,
            purpose="描述故事开始时最重要的地点或环境。",
            story_impact="影响开局和早期场景的空间选择。",
            fill_rule="写具体地点与状态，不要写成抽象主题。",
            example="暴雨后的雁回镇义庄，门外仍有黑伞留下的水痕。",
        ),
        "worldview.core_conflicts": _field(
            label="核心冲突",
            json_type="array<string>",
            import_effective=True,
            purpose="列出世界层面的长期矛盾。",
            story_impact="帮助 GM 选择冲突来源和升级压力。",
            fill_rule="每项写一个清晰冲突，不要堆砌名词。",
            example=["失忆主角与旧案责任", "镇民恐惧与江湖势力封锁"],
        ),
        "script_outline": _field(
            label="剧本总纲",
            json_type="object",
            import_effective=True,
            purpose="保存主线承诺、幕结构、真相地图、线索阶梯和压力时钟。",
            story_impact="这是控制剧情走向、防止跑偏和安排揭露节奏的核心字段。",
            fill_rule="修改时保持 campaign_contract、acts、truth_map、clue_ladder、pressure_clock 互相一致。",
            import_behavior="import_mode=replace_all 时完整覆盖；字段留空或删除会按留空或删除后的结果生效。import_mode=protected 时才使用旧的保护式合并。",
            example={"title": "雾港旧案", "acts": [], "campaign_contract": {}, "truth_map": [], "clue_ladder": [], "pressure_clock": []},
        ),
        "script_outline.title": _field(
            label="剧本标题",
            json_type="string",
            import_effective=True,
            purpose="剧本内部标题，可与游戏标题一致。",
            story_impact="作为剧本层锚点，影响导出和 GM 对主线的识别。",
            fill_rule="保持简短。",
            example="雾港旧案",
        ),
        "script_outline.user_brief": _field(
            label="用户创作简报",
            json_type="object",
            import_effective=True,
            purpose="记录用户最初确认的故事背景、核心设定、必须内容和禁止点。",
            story_impact="是保护用户创作意图的关键来源。",
            fill_rule="除非用户明确修改原始需求，否则不要删除或弱化。",
            import_behavior="import_mode=replace_all 时按 JSON 原样覆盖；如果删除或清空，旧用户简报不会自动恢复。",
            example={"must_include": ["红伞女人"], "forbidden_content": ["不要修仙飞升"]},
        ),
        "script_outline.user_brief.story_background": _field(
            label="用户确认的故事背景",
            json_type="string",
            import_effective=True,
            purpose="保存用户认可的背景前提。",
            story_impact="帮助 GM 区分原始设定和后续即兴内容。",
            fill_rule="只写已确认背景，不写新扩展。",
            example="主角在雨夜义庄醒来，记忆缺失。",
        ),
        "script_outline.user_brief.core_premise": _field(
            label="用户确认的核心设定",
            json_type="string",
            import_effective=True,
            purpose="保存最不可丢失的核心创意。",
            story_impact="影响长期剧情是否仍像用户想要的那一局。",
            fill_rule="一句话写清核心幻想或核心钩子。",
            example="失忆镖师追查自己曾护送的神秘账册。",
        ),
        "script_outline.user_brief.must_include": _field(
            label="必须出现内容",
            json_type="array<string>",
            import_effective=True,
            purpose="列出用户要求必须保留的人、物、桥段、机制或关系。",
            story_impact="GM 和生成器应长期保留这些元素。",
            fill_rule="每项写一个明确要求。",
            example=["雨夜义庄", "黑伞客", "旧案账册"],
        ),
        "script_outline.user_brief.forbidden_content": _field(
            label="用户禁止点",
            json_type="array<string>",
            import_effective=True,
            purpose="记录用户明确不想看到的方向。",
            story_impact="用于防止题材和剧情跑偏。",
            fill_rule="写具体禁止项。",
            example=["不要修仙飞升", "不要变成大规模门派战争"],
        ),
        "script_outline.user_brief.playstyle_preferences": _field(
            label="玩法偏好",
            json_type="array<string>",
            import_effective=True,
            purpose="记录用户偏好的玩法方式。",
            story_impact="影响 GM 更常提供哪类行动机会。",
            fill_rule="写调查、社交、探索、战斗、经营等偏好。",
            example=["调查推理", "关系博弈", "低频但危险的战斗"],
        ),
        "script_outline.user_brief.tone_preferences": _field(
            label="风格偏好",
            json_type="array<string>",
            import_effective=True,
            purpose="记录用户偏好的叙事味道。",
            story_impact="影响语言风格和场面强度。",
            fill_rule="写明确风格词。",
            example=["克制", "压抑", "江湖旧事感"],
        ),
        "script_outline.user_brief.raw_user_input": _field(
            label="用户原始输入",
            json_type="string",
            import_effective=True,
            purpose="保存最初输入的原文参考。",
            story_impact="当结构化字段有歧义时，AI 可回看原意。",
            fill_rule="通常不要改，除非用户明确要求修正原始记录。",
            example="我想玩一个失忆镖师调查义庄旧案的故事。",
        ),
        "script_outline.acts[]": _field(
            label="幕结构计划",
            json_type="array<object>",
            import_effective=True,
            purpose="定义各幕目标、压力、允许揭露和完成条件。",
            story_impact="控制剧情推进节奏，防止过早跳到终局。",
            fill_rule="每幕要有 objective、allowed_reveals、forbidden_reveals、completion_signal；建议补 completion_anchors 和 transition_to_next_act。",
            example=[{"id": "act_1", "name": "雨夜义庄", "objective": "查明醒来现场发生了什么"}],
        ),
        "script_outline.acts[].id": _field(
            label="幕 ID",
            json_type="string",
            import_effective=True,
            purpose="让系统识别当前幕和后续幕。",
            story_impact="campaign_contract.current_act 会引用它。",
            fill_rule="使用 act_1、act_2 这类稳定短 ID。",
            example="act_1",
        ),
        "script_outline.acts[].name": _field(
            label="幕名称",
            json_type="string",
            import_effective=True,
            purpose="给一幕一个可读名称。",
            story_impact="帮助 AI 理解本幕主题。",
            fill_rule="简短具体。",
            example="雨夜义庄",
        ),
        "script_outline.acts[].objective": _field(
            label="本幕目标",
            json_type="string",
            import_effective=True,
            purpose="说明玩家在这一幕应推进的主要目标。",
            story_impact="GM 会围绕目标给线索、压力和行动选项。",
            fill_rule="写玩家可行动的目标，不写抽象主题。",
            example="确认主角为何出现在义庄，并找到离开前的第一条线索。",
        ),
        "script_outline.acts[].dramatic_question": _field(
            label="本幕戏剧问题",
            json_type="string",
            import_effective=True,
            purpose="定义这一幕要吊住玩家的问题。",
            story_impact="帮助 GM 保持悬念而不是直接给答案。",
            fill_rule="用问句或清晰悬念表达。",
            example="主角醒来前到底把什么东西交给了谁？",
        ),
        "script_outline.acts[].pressure": _field(
            label="本幕压力",
            json_type="string",
            import_effective=True,
            purpose="说明主动逼近玩家的危险或倒计时。",
            story_impact="推动剧情，不让场景停滞。",
            fill_rule="写清压力来源和逼近方式。",
            example="镇上的巡夜人开始搜查义庄，黑伞客也在附近出现。",
        ),
        "script_outline.acts[].must_hit_beats": _field(
            label="必须命中的节点",
            json_type="array<string>",
            import_effective=True,
            purpose="列出这一幕必须发生、发现或铺垫的关键节点。",
            story_impact="确保重要剧情不会被即兴生成漏掉。",
            fill_rule="每项写一个具体节点。",
            example=["发现门槛内侧的新鲜泥痕", "听见棺内有第二次敲击"],
        ),
        "script_outline.acts[].allowed_reveals": _field(
            label="允许揭露",
            json_type="array<string>",
            import_effective=True,
            purpose="说明本幕可以让玩家知道的信息。",
            story_impact="控制揭露节奏。",
            fill_rule="只写本幕可公开的信息，不要放最终答案。",
            example=["账册存在", "黑伞客曾到过义庄"],
        ),
        "script_outline.acts[].forbidden_reveals": _field(
            label="禁止提前揭露",
            json_type="array<string>",
            import_effective=True,
            purpose="说明本幕不能直接告诉玩家的真相。",
            story_impact="防止 GM 过早剧透。",
            fill_rule="写明确真相点。",
            example=["账册真正持有人", "黑伞契约的完整规则"],
        ),
        "script_outline.acts[].relationship_turn": _field(
            label="关系变化",
            json_type="string",
            import_effective=True,
            purpose="规划本幕关键人物关系的转折方向。",
            story_impact="帮助社交和同伴剧情有长期弧线。",
            fill_rule="写关系从什么状态向什么状态变化。",
            example="义庄守夜人从戒备转为愿意透露半句旧案。",
        ),
        "script_outline.acts[].escalation_limit": _field(
            label="升级上限",
            json_type="string",
            import_effective=True,
            purpose="限制本幕危机最多升级到什么程度。",
            story_impact="防止第一幕直接变成终局大战或全城崩坏。",
            fill_rule="明确写不能超过的危机层级。",
            example="最多出现追捕和短暂冲突，不引爆全镇围剿。",
        ),
        "script_outline.acts[].completion_signal": _field(
            label="进入下一幕条件",
            json_type="string",
            import_effective=True,
            purpose="说明何时可以认为本幕完成。",
            story_impact="帮助 GM 判断是否推进当前幕。",
            fill_rule="写可观察的达成条件。",
            example="玩家取得账册残页，并知道下一个地点是旧渡口。",
        ),
        "script_outline.acts[].completion_anchors": _field(
            label="当前幕完成锚点",
            json_type="array<object>",
            import_effective=True,
            purpose="把一幕拆成若干真正需要发生的完成锚点，用于判断是否具备进入下一幕的条件。",
            story_impact="未完成 required 锚点时，GM 不应进入下一幕；完成后可以自然过渡但不强制转场。",
            fill_rule="每个锚点写稳定 id、可读 title、required、completion_signal；锚点是通行条件，不是任务清单。",
            example=[{"id": "act_1_anchor_1", "title": "发现异常痕迹", "required": True, "completion_signal": "玩家发现门槛泥痕或棺木底部湿泥"}],
        ),
        "script_outline.acts[].completion_anchors[].id": _field(
            label="锚点 ID",
            json_type="string",
            import_effective=True,
            purpose="让运行时状态记录哪个锚点已经完成。",
            story_impact="ID 会写入 story_progress.completed_anchors，用于判断 required 锚点是否齐备。",
            fill_rule="使用稳定短 ID，例如 act_1_anchor_1；导入后不要随意改名，否则旧进度无法对应。",
            example="act_1_anchor_1",
        ),
        "script_outline.acts[].completion_anchors[].title": _field(
            label="锚点标题",
            json_type="string",
            import_effective=True,
            purpose="给锚点一个人和 AI 都容易理解的名称。",
            story_impact="帮助 GM 知道当前幕还缺哪类关键事件。",
            fill_rule="短句描述事件，不要写长段剧情。",
            example="确认人为遮掩",
        ),
        "script_outline.acts[].completion_anchors[].required": _field(
            label="是否必要锚点",
            json_type="boolean",
            import_effective=True,
            purpose="标记这个锚点是否必须完成后才允许进入下一幕。",
            story_impact="required=true 的锚点未完成时，ready_for_next_act 不会变成 true。",
            fill_rule="关键证据、关键选择、关键关系转折填 true；氛围或可选发现填 false。",
            example=True,
        ),
        "script_outline.acts[].completion_anchors[].completion_signal": _field(
            label="锚点完成信号",
            json_type="string",
            import_effective=True,
            purpose="描述什么具体剧情结果算这个锚点完成。",
            story_impact="状态提取器会根据 GM 输出判断是否把该锚点记为完成。",
            fill_rule="写已经发生且可观察的条件，不写 AI 应该强行安排的任务。",
            example="玩家确认有人近期进入义庄并清理过现场。",
        ),
        "script_outline.acts[].completion_anchors[].story_effect": _field(
            label="锚点剧情效果",
            json_type="string",
            import_effective=True,
            purpose="说明锚点完成后允许 GM 加强或转向哪些剧情。",
            story_impact="帮助 AI 在完成锚点后自然改变线索、压力或 NPC 反应。",
            fill_rule="写完成后的叙事许可或后果，不要写状态 JSON。",
            example="允许 GM 把黑伞客线索从传闻推进到可追踪证据。",
        ),
        "script_outline.acts[].transition_to_next_act": _field(
            label="下一幕过渡规则",
            json_type="object",
            import_effective=True,
            purpose="定义当前幕具备完成条件后如何进入下一幕。",
            story_impact="控制过渡目标和过渡方式，避免强制传送或突然跳幕。",
            fill_rule="填写 target_act、allowed_when 和 transition_style。",
            example={"target_act": "act_2", "allowed_when": "required_anchors_completed", "transition_style": "自然过渡，不强制玩家离开当前场景"},
        ),
        "script_outline.acts[].transition_to_next_act.target_act": _field(
            label="目标下一幕",
            json_type="string",
            import_effective=True,
            purpose="指出当前幕完成后可以过渡到哪一幕。",
            story_impact="GM 和状态提取器会用它理解自然过渡方向。",
            fill_rule="填写后续 acts[].id 中存在的 ID。",
            example="act_2",
        ),
        "script_outline.acts[].transition_to_next_act.allowed_when": _field(
            label="允许过渡条件",
            json_type="string",
            import_effective=True,
            purpose="说明什么时候允许进入下一幕。",
            story_impact="默认 required_anchors_completed，表示必要锚点完成后才具备过渡资格。",
            fill_rule="目前建议使用 required_anchors_completed。",
            example="required_anchors_completed",
        ),
        "script_outline.acts[].transition_to_next_act.transition_style": _field(
            label="过渡风格",
            json_type="string",
            import_effective=True,
            purpose="说明进入下一幕时应保持什么叙事方式。",
            story_impact="避免 AI 突然把玩家强制带离当前场景。",
            fill_rule="写自然转场原则，例如保留玩家选择、先收束当前场景、不要强制传送。",
            example="自然过渡，不强制传送玩家离开当前场景。",
        ),
        "script_outline.campaign_contract": _field(
            label="长期战役契约",
            json_type="object",
            import_effective=True,
            purpose="锁定本局最核心的玩家幻想、悬念、强约束和禁止偏离方向。",
            story_impact="这是 GM 防跑偏的长期锚点。",
            fill_rule="必须具体，不要写成泛泛原则；改它时同步改相关幕结构和素材。",
            import_behavior="import_mode=replace_all 时按 JSON 原样覆盖；如果删除 must_preserve、must_not_become 或 forbidden_drift，旧值不会自动恢复。",
            example={"player_fantasy": "失忆镖师追查旧案", "central_question": "主角失忆前到底护送了什么？"},
        ),
        "script_outline.campaign_contract.premise": _field(
            label="核心前提",
            json_type="string",
            import_effective=True,
            purpose="一句话定义本局最核心的剧本承诺。",
            story_impact="影响所有后续剧情是否围绕同一个核心。",
            fill_rule="写具体玩家处境、冲突和承诺。",
            example="失忆镖师在义庄醒来，必须追查自己护送账册导致的旧案。",
        ),
        "script_outline.campaign_contract.player_fantasy": _field(
            label="玩家核心幻想",
            json_type="string",
            import_effective=True,
            purpose="说明玩家想体验的身份、能力和戏剧位置。",
            story_impact="影响 GM 给玩家的选择感和爽点。",
            fill_rule="从玩家体验角度写，不要只写世界背景。",
            example="以冷静镖师身份抽丝剥茧，靠观察和人情债揭开江湖旧案。",
        ),
        "script_outline.campaign_contract.central_question": _field(
            label="核心悬念",
            json_type="string",
            import_effective=True,
            purpose="贯穿全剧的主要问题。",
            story_impact="GM 会围绕它安排线索和揭露。",
            fill_rule="写一个长期问题，不要在字段里直接回答。",
            example="沈砚失忆前到底护送了什么？",
        ),
        "script_outline.campaign_contract.emotional_arc": _field(
            label="情绪弧线",
            json_type="string",
            import_effective=True,
            purpose="定义玩家体验从什么情绪走向什么情绪。",
            story_impact="影响剧情张力和结局调性。",
            fill_rule="写起点、过程和目标情绪。",
            example="从困惑和不信任，走向承担旧债并主动选择真相。",
        ),
        "script_outline.campaign_contract.must_preserve": _field(
            label="必须保留",
            json_type="array<string>",
            import_effective=True,
            purpose="记录绝不能被后续生成丢掉的设定。",
            story_impact="是强约束之一。",
            fill_rule="每项写具体元素；不要写泛泛的好看、丰富。",
            example=["雨夜义庄", "黑伞客", "失忆镖师身份"],
        ),
        "script_outline.campaign_contract.must_not_become": _field(
            label="禁止变成",
            json_type="array<string>",
            import_effective=True,
            purpose="说明本局不能滑向的类型或剧情方向。",
            story_impact="防止题材跑偏。",
            fill_rule="写具体禁止方向。",
            example=["修仙飞升爽文", "全城战争主线"],
        ),
        "script_outline.campaign_contract.tone_do": _field(
            label="必须保持的味道",
            json_type="array<string>",
            import_effective=True,
            purpose="定义应该保留的风格元素。",
            story_impact="影响 GM 文风和场景选择。",
            fill_rule="写可执行的风格要求。",
            example=["克制", "线索驱动", "江湖旧账感"],
        ),
        "script_outline.campaign_contract.tone_dont": _field(
            label="不能滑向的味道",
            json_type="array<string>",
            import_effective=True,
            purpose="定义不希望出现的风格倾向。",
            story_impact="防止文风偏离。",
            fill_rule="写明确不要的风格。",
            example=["无厘头", "热血喊招式", "过度卖弄设定"],
        ),
        "script_outline.campaign_contract.act_plan": _field(
            label="幕计划副本",
            json_type="array<object>",
            import_effective=True,
            purpose="给战役契约内保留一份幕结构参考。",
            story_impact="帮助 GM 在长期上下文中保持幕结构稳定。",
            fill_rule="应与 script_outline.acts 保持一致。",
            example=[{"id": "act_1", "name": "雨夜义庄"}],
        ),
        "script_outline.campaign_contract.relationship_arcs": _field(
            label="关系线",
            json_type="array<object|string>",
            import_effective=True,
            purpose="规划关键人物关系如何变化。",
            story_impact="影响社交、同伴、背叛和信任剧情。",
            fill_rule="写清人物、起点、变化和可能结果。",
            example=["守夜人从敌意到有限协助"],
        ),
        "script_outline.campaign_contract.forbidden_drift": _field(
            label="禁止偏离",
            json_type="array<string>",
            import_effective=True,
            purpose="记录长期不能偏离的方向。",
            story_impact="漂移校验和 GM 都会参考它防止跑偏。",
            fill_rule="比 must_not_become 更具体地写跑偏风险。",
            example=["不要把黑伞客改成无关的妖魔势力", "不要跳过账册线索直接公布幕后主使"],
        ),
        "script_outline.campaign_contract.canon_terms": _field(
            label="正典词条",
            json_type="array<string>",
            import_effective=True,
            purpose="锁定角色名、地点名、组织名、物品名等专有名词。",
            story_impact="减少 AI 改名、误写、同物多名。",
            fill_rule="填写要长期保持一致的名称。",
            example=["沈砚", "雁回镇", "黑伞客", "旧案账册"],
        ),
        "script_outline.campaign_contract.pacing_rules": _field(
            label="节奏规则",
            json_type="array<string>",
            import_effective=True,
            purpose="规定线索、战斗、揭露和转场的节奏。",
            story_impact="影响回合推进速度和悬念保留。",
            fill_rule="写可执行规则。",
            example=["每 2 到 3 回合推进一个可验证线索", "第一幕不揭露账册真凶"],
        ),
        "script_outline.campaign_contract.current_act": _field(
            label="当前幕",
            json_type="string",
            import_effective=True,
            purpose="告诉 GM 当前主要处于哪一幕。",
            story_impact="影响本回合允许揭露和目标判断。",
            fill_rule="填写 acts[].id 中存在的 ID。",
            example="act_1",
        ),
        "script_outline.director_contract": _field(
            label="导演契约",
            json_type="object",
            import_effective=True,
            purpose="保存更偏导演层面的推进、镜头、冲突或结构规则。",
            story_impact="影响 Story Director 给 GM 的本回合导演建议。",
            fill_rule="写长期有效的导演规则，不要写单回合临时输出。",
            example={"reveal_policy": "线索先于答案，压力先于决战。"},
        ),
        "script_outline.story_contract": _field(
            label="叙事契约",
            json_type="object",
            import_effective=True,
            purpose="保存文风、节奏、叙事视角和阅读体验规则。",
            story_impact="影响 GM narrative 的语气、密度和节奏。",
            fill_rule="适合写 tone、pacing 等风格规则。",
            example={"tone": "冷峻克制", "pacing": "慢燃调查，关键节点加速"},
        ),
        "script_outline.truth_map[]": _field(
            label="真相地图",
            json_type="array<object>",
            import_effective=True,
            purpose="保存 GM 知道但玩家需要逐步发现的幕后真相。",
            story_impact="决定悬疑、秘密和最终揭露的真实结构。",
            fill_rule="不要把 truth 直接写进公开字段；每条真相都应有表象和揭露条件。",
            example=[{"truth": "账册记录黑伞契约名单", "public_mask": "一本普通镖局账册", "reveal_condition": "找到缺页并对照货单"}],
        ),
        "script_outline.truth_map[].truth": _field(
            label="幕后真相",
            json_type="string",
            import_effective=True,
            purpose="GM 需要知道的真实答案。",
            story_impact="决定长期谜底和反转。",
            fill_rule="写给 GM，不要让它出现在玩家公开信息里。",
            example="旧案账册记录了雁回镇三家势力共同签下的黑伞契约。",
        ),
        "script_outline.truth_map[].public_mask": _field(
            label="公开表象",
            json_type="string",
            import_effective=True,
            purpose="玩家早期看到的误导或表层解释。",
            story_impact="支持悬疑和逐步揭露。",
            fill_rule="写玩家可见但不完整的信息。",
            example="账册看似只是镖局亏空记录。",
        ),
        "script_outline.truth_map[].reveal_condition": _field(
            label="揭露条件",
            json_type="string",
            import_effective=True,
            purpose="定义何时允许揭露这一真相。",
            story_impact="控制真相不会过早暴露。",
            fill_rule="写具体条件，例如找到某线索、达成某关系、进入某幕。",
            example="玩家取得缺页，并让守夜人承认当年押镖路线。",
        ),
        "script_outline.clue_ladder[]": _field(
            label="线索阶梯",
            json_type="array<object>",
            import_effective=True,
            purpose="安排线索从表层到深层的递进。",
            story_impact="决定调查玩法是否有层次。",
            fill_rule="每条线索要指向下一步，但不要直接揭穿最终真相。",
            example=[{"stage": "第一层", "clue": "门槛内侧有新鲜泥痕", "points_to": "有人从义庄内部离开", "do_not_reveal": "离开者身份"}],
        ),
        "script_outline.clue_ladder[].stage": _field(
            label="线索阶段",
            json_type="string",
            import_effective=True,
            purpose="标记线索递进层级。",
            story_impact="帮助 GM 控制调查顺序。",
            fill_rule="使用第一层、第二层或 act_1_mid 等清晰阶段。",
            example="第一层",
        ),
        "script_outline.clue_ladder[].clue": _field(
            label="玩家可发现线索",
            json_type="string",
            import_effective=True,
            purpose="玩家通过行动可以看见、听见、推理出的证据。",
            story_impact="直接影响调查回合内容。",
            fill_rule="写可观察线索，不写 GM 解释。",
            example="门槛内侧有新鲜泥痕。",
        ),
        "script_outline.clue_ladder[].points_to": _field(
            label="线索指向",
            json_type="string",
            import_effective=True,
            purpose="说明这条线索把玩家引向哪里或什么矛盾。",
            story_impact="帮助 GM 给出下一步行动方向。",
            fill_rule="指向人物、地点、物件、时间矛盾或下一条线索。",
            example="义庄后门和旧渡口。",
        ),
        "script_outline.clue_ladder[].do_not_reveal": _field(
            label="本阶段不能揭露",
            json_type="string",
            import_effective=True,
            purpose="限制这条线索不能直接说出的答案。",
            story_impact="保留悬念。",
            fill_rule="写一个明确不能说破的真相点。",
            example="不能直接说守夜人就是当年押镖目击者。",
        ),
        "script_outline.pressure_clock[]": _field(
            label="压力时钟",
            json_type="array<object>",
            import_effective=True,
            purpose="记录会随玩家行动或时间推进而升级的压力来源。",
            story_impact="让剧情有外部推动力和后果。",
            fill_rule="每个压力要有推进条件、后果和可见性。",
            example=[{"name": "巡夜搜查", "tick_condition": "玩家拖延或制造声响", "consequence": "义庄被封锁", "visibility": "public"}],
        ),
        "script_outline.pressure_clock[].name": _field(
            label="压力名称",
            json_type="string",
            import_effective=True,
            purpose="标记压力来源。",
            story_impact="帮助 GM 识别正在升级的危险。",
            fill_rule="简短具体。",
            example="巡夜搜查",
        ),
        "script_outline.pressure_clock[].tick_condition": _field(
            label="推进条件",
            json_type="string",
            import_effective=True,
            purpose="说明什么情况下压力前进一格或升级。",
            story_impact="让玩家选择产生后果。",
            fill_rule="写可判断条件。",
            example="玩家长时间停留、制造明显声响或放走关键证人。",
        ),
        "script_outline.pressure_clock[].consequence": _field(
            label="升级后果",
            json_type="string",
            import_effective=True,
            purpose="说明压力推进后的剧情结果。",
            story_impact="影响风险、场景变化和 NPC 行动。",
            fill_rule="写具体后果，不要只写危险增加。",
            example="巡夜人封锁义庄，玩家必须从后院或棺材暗道离开。",
        ),
        "script_outline.pressure_clock[].visibility": _field(
            label="压力可见性",
            json_type="string",
            import_effective=True,
            purpose="说明玩家是否能感知这个压力。",
            story_impact="决定 GM 是公开提示还是幕后推进。",
            fill_rule="使用 public、mixed 或 gm_only。",
            accepted_values=["public", "mixed", "gm_only"],
            example="mixed",
        ),
        "script_outline.mechanics_contract[]": _field(
            label="机制契约",
            json_type="array<object>",
            import_effective=True,
            purpose="保存需要长期遵守的玩法机制、成长规则、资源限制或特殊判定。",
            story_impact="影响 GM 如何处理能力、代价、成长和失败后果。",
            fill_rule="每条机制写 name、rule、progression、visibility；重要机制也应同步到 lore_entries。",
            example=[{"name": "黑伞债", "rule": "每次借用黑伞力量都会留下可追踪代价", "progression": "三次后触发债主登场", "visibility": "mixed"}],
        ),
        "lore_entries[]": _field(
            label="剧本素材条目",
            json_type="array<object>",
            import_effective=True,
            purpose="保存可被检索、常驻或按触发词注入给 GM 的人物、地点、势力、物品、线索、秘密、机制等素材。",
            story_impact="直接影响每回合 GM 能想起哪些设定和线索。",
            fill_rule="每条要有 title 和 content；线索/秘密类要清楚区分 public_info、gm_secret 和 usage_note。",
            import_behavior="导入会覆盖本游戏现有剧本素材，并重新生成 embedding。",
            example=[{"title": "义庄", "type": "location", "content": "义庄暗藏旧案账册线索。"}],
        ),
        "lore_entries[].title": _field(
            label="素材标题",
            json_type="string",
            import_effective=True,
            purpose="这条剧本素材的名称。",
            story_impact="影响检索和 AI 理解。",
            fill_rule="必须非空；用具体名称。",
            example="雁回镇义庄",
        ),
        "lore_entries[].type": _field(
            label="素材类型",
            json_type="string|null",
            import_effective=True,
            purpose="标记素材类别。",
            story_impact="帮助 UI 分组，也帮助 AI 理解用途。",
            fill_rule="建议使用 core_rule、protagonist、npc、faction、location、item、plot_hook、mechanic、secret、clue、pressure、twist。",
            accepted_values=["core_rule", "protagonist", "npc", "faction", "location", "item", "plot_hook", "mechanic", "secret", "clue", "pressure", "twist"],
            example="clue",
        ),
        "lore_entries[].keywords": _field(
            label="关键词",
            json_type="array<string>",
            import_effective=True,
            purpose="帮助语义和关键词检索命中这条素材。",
            story_impact="影响相关素材是否会被召回。",
            fill_rule="写玩家可能输入、GM 可能提到的关键词。",
            example=["义庄", "账册", "黑伞"],
        ),
        "lore_entries[].trigger_words": _field(
            label="触发词",
            json_type="array<string>",
            import_effective=True,
            purpose="当玩家输入包含这些词时，更容易注入该素材。",
            story_impact="影响素材进入 GM prompt 的时机。",
            fill_rule="写具体可匹配词，不要写太泛的词。",
            example=["搜义庄", "检查棺材", "黑伞客"],
        ),
        "lore_entries[].priority": _field(
            label="注入优先级",
            json_type="string|null",
            import_effective=True,
            purpose="控制这条素材被优先考虑的程度。",
            story_impact="高优先级素材更容易进入上下文。",
            fill_rule="使用 low、medium、high 或 critical。",
            accepted_values=["low", "medium", "high", "critical"],
            example="high",
        ),
        "lore_entries[].always_on": _field(
            label="常驻注入",
            json_type="boolean",
            import_effective=True,
            purpose="决定这条素材是否总是尽量进入 GM 上下文。",
            story_impact="适合核心规则、主角身份、不能忘的强约束；过多会增加 token 消耗。",
            fill_rule="只给真正核心的条目设为 true。",
            example=True,
        ),
        "lore_entries[].visibility": _field(
            label="素材可见性",
            json_type="string|null",
            import_effective=True,
            purpose="说明素材是公开、幕后还是混合信息。",
            story_impact="帮助 GM 判断能否直接说给玩家。",
            fill_rule="使用 public、mixed 或 gm_only。",
            accepted_values=["public", "mixed", "gm_only"],
            example="mixed",
        ),
        "lore_entries[].public_info": _field(
            label="公开信息",
            json_type="string|null",
            import_effective=True,
            purpose="玩家已经知道或可以公开得知的信息。",
            story_impact="GM 可以直接呈现或让 NPC 说出。",
            fill_rule="不要写隐藏真相。",
            example="雁回镇义庄多年无人愿靠近，雨夜常有守夜铃声。",
        ),
        "lore_entries[].gm_secret": _field(
            label="GM 秘密",
            json_type="string|null",
            import_effective=True,
            purpose="GM 需要知道但不能直接告诉玩家的幕后信息。",
            story_impact="支撑伏笔、反转和一致性。",
            fill_rule="只能作为幕后依据；如果要给玩家，必须转化为线索。",
            example="义庄地下藏着账册缺页，守夜人知道入口。",
        ),
        "lore_entries[].content": _field(
            label="注入内容",
            json_type="string",
            import_effective=True,
            purpose="真正注入给 GM 使用的完整素材正文。",
            story_impact="直接影响 GM 每回合可用的设定。",
            fill_rule="必须非空；写清事实、限制和可用玩法，不要过长。",
            example="义庄是旧案关键地点。玩家检查棺材、门槛或后院时，应发现指向旧渡口的线索，但不能直接揭露账册主人。",
        ),
        "lore_entries[].usage_note": _field(
            label="使用说明",
            json_type="string|null",
            import_effective=True,
            purpose="告诉 GM 何时使用这条素材、如何呈现、不能泄露什么。",
            story_impact="提高素材使用的准确性，降低剧透风险。",
            fill_rule="写触发时机、呈现方式和禁忌。",
            example="当玩家调查义庄细节时使用；给可观察痕迹，不直接说出守夜人的真实身份。",
        ),
        "lore_entries[].is_active": _field(
            label="是否启用",
            json_type="boolean",
            import_effective=True,
            purpose="控制这条素材是否参与检索和注入。",
            story_impact="关闭后 GM 不会主动使用该素材。",
            fill_rule="仍需要保留但暂时不用的条目设为 false。",
            example=True,
        ),
        "modes[]": _field(
            label="行动风格规则",
            json_type="array<object>",
            import_effective=True,
            purpose="保存不同玩家行动类型下 GM 应遵循的处理规则。",
            story_impact="影响调查、社交、探索、战斗等不同模式的回合风格。",
            fill_rule="每条要有 name 和 injection；triggers 用于匹配玩家输入。",
            import_behavior="导入会覆盖本游戏现有行动风格规则。",
            example=[{"name": "调查模式", "triggers": ["调查", "检查"], "injection": "给线索和可验证细节，不直接给最终答案。"}],
        ),
        "modes[].name": _field(
            label="规则名称",
            json_type="string",
            import_effective=True,
            purpose="行动风格规则的名称。",
            story_impact="帮助 AI 识别当前处理模式。",
            fill_rule="必须非空；使用主线、调查、社交、探索、战斗等清晰名称。",
            example="调查模式",
        ),
        "modes[].triggers": _field(
            label="触发词",
            json_type="array<string>",
            import_effective=True,
            purpose="玩家输入包含这些词时更容易选中该模式。",
            story_impact="影响哪条行动规则被应用。",
            fill_rule="写具体动作词，不要写太泛。",
            example=["调查", "检查", "搜索", "追问"],
        ),
        "modes[].injection": _field(
            label="注入规则",
            json_type="string",
            import_effective=True,
            purpose="该模式下 GM 必须遵守的具体导演规则。",
            story_impact="直接影响该类行动的叙事结果和选项设计。",
            fill_rule="写成可执行规则，不要写空泛口号。",
            example="调查时给出可观察线索、矛盾细节和下一步方向；不要直接宣布幕后真相。",
        ),
        "modes[].priority": _field(
            label="模式优先级",
            json_type="string|null",
            import_effective=True,
            purpose="多个模式匹配时的优先考虑程度。",
            story_impact="影响规则选择。",
            fill_rule="使用 low、medium 或 high。",
            accepted_values=["low", "medium", "high"],
            example="medium",
        ),
        "modes[].enabled": _field(
            label="是否启用",
            json_type="boolean",
            import_effective=True,
            purpose="控制该行动风格规则是否参与匹配。",
            story_impact="关闭后该类规则不会被选中。",
            fill_rule="需要暂时停用时设为 false。",
            example=True,
        ),
        "characters[]": _field(
            label="角色导演档案",
            json_type="array<object>",
            import_effective=True,
            purpose="保存角色姓名、公开身份、外貌、导演档案和可见性等剧本级角色设定。",
            story_impact="影响角色页展示、角色一致性、后续角色同步，以及 GM 对人物动机和关系弧线的理解。",
            fill_rule="每条必须有 name；改角色名时同步 canon_terms、lore_entries 和 script_outline 中的称呼。",
            import_behavior="import_mode=replace_all 时覆盖角色导演档案；不会复制头像文件本身、回合历史、当前状态或角色运行时进度。",
            example=[{"id": "00000000-0000-0000-0000-000000000000", "name": "沈砚", "role": "protagonist", "identity": "失忆镖师"}],
        ),
        "characters[].id": _field(
            label="角色 ID",
            json_type="string",
            import_effective=True,
            purpose="用于导入时匹配当前游戏中已有角色。",
            story_impact="匹配成功时可以在改名或改档案时保留该角色已有头像文件字段。",
            fill_rule="同一游戏导出再导入时保持原值；复制到其他游戏时可以保留或删除，系统找不到匹配角色会创建新角色。",
            import_behavior="导入时只用于匹配已有角色；不会把不存在的 id 强行写入新角色。",
            example="00000000-0000-0000-0000-000000000000",
        ),
        "characters[].name": _field(
            label="角色姓名",
            json_type="string",
            import_effective=True,
            purpose="角色的主显示名和唯一名称。",
            story_impact="影响角色页、角色同步、GM 识别人物和正典称呼。",
            fill_rule="必须非空；如需长期改名，同时修改 canon_terms、lore_entries 和 script_outline。",
            example="沈砚",
        ),
        "characters[].aliases": _field(
            label="角色别名",
            json_type="array<string>",
            import_effective=True,
            purpose="记录同一角色的其他称呼。",
            story_impact="帮助 AI 理解称呼变化，减少误把同一人物写成不同角色。",
            fill_rule="每项写一个别名；如果别名很重要，也同步写入 canon_terms 或 lore_entries。",
            example=["沈镖头"],
        ),
        "characters[].role": _field(
            label="角色定位",
            json_type="string|null",
            import_effective=True,
            purpose="说明角色是主角、NPC、同伴或其他。",
            story_impact="影响角色排序、角色同步优先级和 GM 对人物戏份的判断。",
            fill_rule="使用 protagonist、npc、companion 或 other；如需改变主线定位，也同步改 script_outline 和 lore_entries。",
            accepted_values=["protagonist", "npc", "companion", "other"],
            example="protagonist",
        ),
        "characters[].identity": _field(
            label="公开身份",
            json_type="string|null",
            import_effective=True,
            purpose="角色对玩家可见的身份。",
            story_impact="影响角色页显示和 GM 对玩家已知人物关系的描述。",
            fill_rule="写玩家可见身份，不要直接写隐藏真相；隐藏身份写到 gm_secret、truth_map 或 story_profile 的幕后字段。",
            example="失忆镖师",
        ),
        "characters[].description": _field(
            label="角色描述",
            json_type="string|null",
            import_effective=True,
            purpose="角色概述参考。",
            story_impact="影响 AI 对角色性格、能力和剧情功能的理解。",
            fill_rule="写稳定设定；关键剧情功能也应同步到 lore_entries[].content 或 campaign_contract.relationship_arcs。",
            example="冷静寡言，擅长观察押镖痕迹。",
        ),
        "characters[].appearance": _field(
            label="外貌描述",
            json_type="string|null",
            import_effective=True,
            purpose="角色视觉参考。",
            story_impact="影响角色页和 GM 描写人物出场时的视觉一致性。",
            fill_rule="写稳定外貌特征；它不会替换已经上传的头像文件。",
            example="眉骨锋利，旧伤横过左肩。",
        ),
        "characters[].story_profile": _field(
            label="导演档案",
            json_type="object|null",
            import_effective=True,
            purpose="角色欲望、恐惧、关系线等导演参考。",
            story_impact="影响人物动机、社交反应、背叛/信任弧线和秘密揭露节奏。",
            fill_rule="建议使用 dramatic_function、desire、fear、leverage、relationship_arc、public_limit；重要内容也同步到 script_outline 或 lore_entries。",
            example={"desire": "查清旧案", "fear": "自己正是旧案帮凶"},
        ),
        "characters[].portrait_prompt": _field(
            label="角色画像提示",
            json_type="string|null",
            import_effective=True,
            purpose="保存生成或重建角色画像时可用的文字描述。",
            story_impact="不直接影响 GM 剧情，但影响角色视觉资产的一致性。",
            fill_rule="写外貌、服装、气质和画面要求；它不会自动生成或替换头像文件。",
            example="冷峻黑衣镖师，雨夜义庄背景，左肩旧伤，克制写实风格。",
        ),
        "characters[].visibility": _field(
            label="角色可见性",
            json_type="string|null",
            import_effective=True,
            purpose="控制角色是否在玩家可见角色列表中显示。",
            story_impact="hidden 适合幕后人物或尚未登场角色；visible 适合玩家已知角色。",
            fill_rule="使用 visible 或 hidden。",
            accepted_values=["visible", "hidden"],
            example="visible",
        ),
        "characters[].is_visible": _field(
            label="是否显示",
            json_type="boolean",
            import_effective=True,
            purpose="控制角色 UI 是否显示该角色。",
            story_impact="通常与 visibility 一致；隐藏角色不会主动出现在玩家可见列表。",
            fill_rule="visible 通常填 true，hidden 通常填 false；如不确定，按 visibility 保持一致。",
            example=True,
        ),
        "characters[].source": _field(
            label="角色来源",
            json_type="string|null",
            import_effective=True,
            purpose="说明角色来自生成、手动创建或其他来源。",
            story_impact="主要影响维护和同步判断，不直接改变剧情。",
            fill_rule="保持 generator、lore、manual、settings_import 等短标签；最多 32 个字符。",
            example="generator",
        ),
        "characters[].sync_meta": _field(
            label="角色同步元数据",
            json_type="object",
            import_effective=True,
            purpose="记录角色字段上一次从剧本素材同步来的值。",
            story_impact="影响以后执行角色同步时，哪些字段会被新剧本素材更新。",
            fill_rule="高级字段。通常保持导出值；如果希望后续同步完全重新判断，可以清空为 {}。",
            import_behavior="replace_all 导入时会覆盖。",
            example={"identity": "失忆镖师", "story_profile": {"desire": "查清旧案"}},
        ),
        "characters[].manual_fields": _field(
            label="手动锁定字段",
            json_type="array<string>",
            import_effective=True,
            purpose="记录哪些角色字段被视为人工修改，后续角色同步不应自动覆盖。",
            story_impact="影响角色资料是否会被 lore_entries 或 script_outline 的变化同步改写。",
            fill_rule="高级字段。可填写 identity、description、appearance、portrait_prompt、visibility、story_profile 或 story_profile.desire 等字段名。",
            import_behavior="replace_all 导入时会覆盖。",
            example=["identity", "appearance", "story_profile.desire"],
        ),
    }

    for key, default in DEFAULT_GENERATION_SETTINGS.items():
        minimum, maximum = SETTING_RANGES[key]
        guide[f"generation_settings.{key}"] = _generation_setting_field(
            key=key,
            default=default,
            minimum=minimum,
            maximum=maximum,
        )

    return guide


def _generation_setting_field(
    *,
    key: str,
    default: int,
    minimum: int,
    maximum: int,
) -> dict[str, Any]:
    labels = {
        "narrative_target_min_chars": "剧情目标最少字数",
        "narrative_target_max_chars": "剧情目标最多字数",
        "narrative_min_chars": "剧情最低字数",
        "paragraph_min": "最少段落",
        "paragraph_max": "最多段落",
        "scene_heading_max": "场景标题上限",
        "emphasis_min": "重点标记最少数量",
        "emphasis_max": "重点标记最多数量",
        "recent_turn_excerpt_chars": "近期回合片段长度",
    }
    purposes = {
        "narrative_target_min_chars": "控制每回合 narrative 正文目标下限。",
        "narrative_target_max_chars": "控制每回合 narrative 正文目标上限。",
        "narrative_min_chars": "控制每回合 narrative 正文硬性最低长度。",
        "paragraph_min": "控制 narrative 建议最少段落数。",
        "paragraph_max": "控制 narrative 建议最多段落数。",
        "scene_heading_max": "控制每回合最多允许几个 Markdown 场景标题。",
        "emphasis_min": "控制每回合建议最少几个加粗重点标记。",
        "emphasis_max": "控制每回合建议最多几个加粗重点标记。",
        "recent_turn_excerpt_chars": "控制传给 GM 的每条近期回合 gm_output 摘录长度。",
    }
    impacts = {
        "narrative_target_min_chars": "数值越高，描写越充分，token 消耗和生成时间也会增加。",
        "narrative_target_max_chars": "数值越高，GM 更容易写长；过高可能拖慢响应。",
        "narrative_min_chars": "防止 GM 输出过短；过高会让简单行动也变得冗长。",
        "paragraph_min": "提高后文本更有层次；过高会让短事件被拆得很碎。",
        "paragraph_max": "降低后阅读更紧凑；过高会增加展开空间。",
        "scene_heading_max": "0 会禁止场景标题；较高会让转场更明显，但可能破坏沉浸。",
        "emphasis_min": "提高后关键线索更醒目，但过多会显得嘈杂。",
        "emphasis_max": "限制加粗数量，避免整段都是重点。",
        "recent_turn_excerpt_chars": "越高越能保留近期叙事细节，但 token 消耗更高；越低越省 token，但近期细节可能丢失。",
    }
    dependencies = {
        "narrative_target_min_chars": "必须小于或等于 narrative_target_max_chars；系统会自动修正异常值。",
        "narrative_target_max_chars": "必须大于或等于 narrative_target_min_chars；系统会自动修正异常值。",
        "narrative_min_chars": "不能高于 narrative_target_min_chars；系统会自动修正异常值。",
        "paragraph_min": "必须小于或等于 paragraph_max；系统会自动修正异常值。",
        "paragraph_max": "必须大于或等于 paragraph_min；系统会自动修正异常值。",
        "emphasis_min": "必须小于或等于 emphasis_max；系统会自动修正异常值。",
        "emphasis_max": "必须大于或等于 emphasis_min；系统会自动修正异常值。",
    }
    return _field(
        label=labels[key],
        json_type="integer",
        import_effective=True,
        purpose=purposes[key],
        story_impact=impacts[key],
        fill_rule=(
            f"填写 {minimum} 到 {maximum} 之间的整数；默认值 {default}。"
            f"{dependencies.get(key, '')}"
        ),
        import_behavior="导入时会归一化为整数，并限制在允许范围内。",
        example=default,
    )


def _field(
    *,
    label: str,
    json_type: str,
    import_effective: bool,
    purpose: str,
    story_impact: str,
    fill_rule: str,
    example: Any,
    import_behavior: str | None = None,
    accepted_values: list[str] | None = None,
) -> dict[str, Any]:
    payload: dict[str, Any] = {
        "label": label,
        "json_type": json_type,
        "import_effective": import_effective,
        "purpose": purpose,
        "story_impact": story_impact,
        "fill_rule": fill_rule,
        "import_behavior": import_behavior
        or ("导入时会覆盖或更新对应设定。" if import_effective else "导入时忽略。"),
        "example": example,
    }
    if accepted_values is not None:
        payload["accepted_values"] = accepted_values
    return payload
